apiVersion: v1
kind: Service
metadata:
  name: {{ include "skillgap.frontendName" . }}
  namespace: {{ include "skillgap.namespaceName" . }}
  labels:
    {{- include "skillgap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "skillgap.frontendName" . }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: container-port


      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillgap.frontendName" . }}
  namespace: {{ include "skillgap.namespaceName" . }}
  labels:
    {{- include "skillgap.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "skillgap.frontendName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "skillgap.frontendName" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: container-port
              containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: PORT
              value: {{ .Values.frontend.service.port | quote }}
            - name: BACKEND_URL
              value: {{ printf "http://%s:%v" (include "skillgap.backendName" .) .Values.backend.service.port | quote }}
            - name: VITE_API_URL
              value: {{ .Values.frontend.env.apiUrl | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: container-port
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: container-port
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}