apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillgap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: skillgap
  source:
    repoURL: https://github.com/zeyadbilal/SkillGap.git
    targetRevision: abdelrahman-deployment
    path: helm/skillgap
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: skillgap-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
