apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: skillgap
  namespace: argocd
spec:
  description: SkillGap application project
  sourceRepos:
    - https://github.com/zeyadbilal/SkillGap.git
  destinations:
    - namespace: skillgap-production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
