replicaCount:
  backend: 1
  frontend: 1
  model: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

namespace:
  appName: skillgap
  environment: production

backend:
  image:
    repository: skillgap-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
  resources: {}
  env:
    nodeEnv: production
    logLevel: info
    pgPoolMax: "20"
    pgPoolMin: "0"

frontend:
  image:
    repository: skillgap-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources: {}

model:
  image:
    repository: skillgap-model
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5001
  resources: {}

external:
  # Railway PostgreSQL connection string, for example postgres://user:password@host:port/db
  postgresUrl: ""
  # Railway Redis connection string, for example rediss://default:password@host:port
  redisUrl: "http://localhost"

secrets:
  jwtSecret: ""

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
  hosts:
    - host: skillgap.abdelrahmanmokhater.me
      paths:
        - path: /
          pathType: Prefix
  tls: []
